---
config:
  s3_bucket: my-bucket
  kms_key_arn: arn:aws:kms:ap-southeast-2:123456789012:key/12309128-23123123-12312312

  codebuild:  
    log_group: 
      enabled: true
      create: true
      name: import:CloudWatchLogGroup
      retention: 7 # days

  iam:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: 
        - arn:aws:s3:::my-bucket/*

sources:
  - name: Source
    from: CodeCommit
    repository: my-repo
    branch: {{vars.BranchName}}
  - name: MySharedLib
    from: CodeCommit
    repository: my-shared-lib
    branch: main


stages:
  - name: Build
    actions:
      - name: Build
        provider: CodeBuild
        buildspec: buildspecs/build.yml
        # 👇 any of the defaults should be overridable on a per-action basis
        compute_type: BUILD_GENERAL1_MEDIUM
        image: another-image
        environment:
          # all actions will get AWS_DEFAULT_REGION/AWS_REGION set to the current region as well
          MY_VAR: MyValue

  - name: DevDeploy
    actions:
      - name: Deploy
        provider: CodeBuild
        commands:
          - make deploy env=dev
        input_artifacts:
          # all actions will get the sources as input artifacts as well
          - Build

  - name: ProdDeploy
    enabled: {{vars.BranchName == "main"}}
    actions:
      - name: ProdDeploy
        provider: CodeBuild
        commands:
          - make deploy env=prod
        input_artifacts:
          - Build
